/*
 * Copyright Debezium Authors.
 *
 * Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
package io.debezium.connector.mongodb;

import java.util.Arrays;

import org.bson.*;
import org.bson.codecs.BsonDocumentCodec;
import org.bson.io.ByteBufferBsonInput;

class RawBytesSerialization {
    private static final String ID_FIELD_NAME = "_id";

    private static RawBsonDocument asRaw(BsonDocument doc) {
        if (!(doc instanceof RawBsonDocument)) {
            // Some documents are generated by the connector, so they need to be serialized.
            //
            doc = new RawBsonDocument(doc, new BsonDocumentCodec());
        }

        return (RawBsonDocument) doc;
    }

    static public byte[] toBytes(BsonDocument doc) {
        ByteBuf byteBuffer = asRaw(doc).getByteBuffer();
        return Arrays.copyOfRange(byteBuffer.array(), 0, byteBuffer.limit());
    }

    static byte[] getBytes(BsonDocument doc, int offset, int length) {
        return Arrays.copyOfRange(asRaw(doc).getByteBuffer().array(), offset, offset + length);
    }

    private static byte[] getIdValue(RawBsonDocument document) {
        try (BsonBinaryReader bsonReader = new BsonBinaryReader(new ByteBufferBsonInput(document.getByteBuffer()))) {
            byte[] bytes;
            bsonReader.readStartDocument();

            BsonType type = bsonReader.readBsonType();
            while (type != BsonType.END_OF_DOCUMENT) {
                if (bsonReader.readName().equals(ID_FIELD_NAME)) {
                    int startPosition = bsonReader.getBsonInput().getPosition();
                    bsonReader.skipValue();
                    int endPosition = bsonReader.getBsonInput().getPosition();
                    int size = endPosition - startPosition;

                    if (type != BsonType.DOCUMENT) {
                        size++;
                    }
                    bytes = getBytes(document, startPosition, size);

                    if (type != BsonType.DOCUMENT) {
                        bytes[size - 1] = (byte) type.getValue();
                    }
                    return bytes;
                }
                bsonReader.skipValue();
                type = bsonReader.readBsonType();
            }

            bsonReader.readEndDocument();
        }

        throw new IllegalStateException("RawBsonDocument '" + ID_FIELD_NAME + "' not found");
    }

    public static byte[] getDocumentId(BsonDocument document) {
        if (document == null) {
            return null;
        }
        return getIdValue(asRaw(document));
    }

    public static byte[] getDocumentValue(BsonDocument document) {
        return toBytes(document);
    }
}
